### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-trigger#1]
Really very, very nice!

Some minor comments/suggestions:

in https://cms-opendata-workshop.github.io/workshop-lesson-trigger/01-introduction/index.html

- [x] when mentioning " these triggers are implemented using CMSSW code" you could remind that CMSSW is used for everything, from the data taking to the analysis. It may have been mentioned earlier, but would be good to repeat in order to avoid confusion. In pre-exercises, for a good reason, the emphasis is on its use in analysis.

in https://cms-opendata-workshop.github.io/workshop-lesson-trigger/02_choosing/index.html

- [x] alo -> also in "Alo, change the PoolSource file;"
- [x] in Challenge: Where - Were in "Where you able to spot it?"

in https://cms-opendata-workshop.github.io/workshop-lesson-trigger/03_prescales/index.html

- [x] In Keypoints: "Prescales can be extracted using the trigger tools in CMSSW and from the brilcalc tool." but there's no mention of brilcalc in this page. Maybe a link? Or a mention that it will be covered later?

**Comment by caredg** [comment]
done for the newest version 2021
